### ISSUE TITLE
Karma / Jest testing

### ISSUE THREAD

**Issue by arthurgeron** [adamhaile/S#15]
Hi, I'm having a hard time setting Karma or Jest to work with S.js.

Do you have any example projects to provide? It'd be awesome if they get included into this repository for future reference.

**Comment by adamhaile** [comment]
S's own test suite uses karma and jasmine (similar test primitives to jest).  Check out the karma.conf.js file and the tests in spec/.  If that doesn't help, say more about what troubles you're having?

**Comment by arthurgeron** [comment]
Ok, I set up the project extremely similar to yours.
I'm using the same jasmine.json, same loadS.js file.
Same karma config.
Same test structure, I've just a simple test there that imports one of my js files (which contains surplus code).

Before adding the "helper" I was getting the "unexpected token" like this: 
 ```
 Unexpected token (11:26)

   9 | const alianzaLogo = require('../../logo.png')
  10 | const loginLabel = S.data('Login')
> 11 | const logo = S.root(() => <img class='alianza-logo' src={S.data(alianzaLogo)()} />)
     |                           ^
  12 | const emailLabel = S.data('E-mail')
  13 | const passwordLabel = S.data('Password')
  14 | const logoutLabel = S.data('Logout')
    at Parser.raise (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:3893:15)
    at Parser.unexpected (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:5222:16)
    at Parser.parseExprAtom (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:6298:20)
    at Parser.parseExprSubscripts (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:5898:21)
    at Parser.parseMaybeUnary (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:5877:21)
    at Parser.parseExprOps (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:5786:21)
    at Parser.parseMaybeConditional (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:5758:21)
    at Parser.parseMaybeAssign (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:5705:21)
    at Parser.parseFunctionBody (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:6887:24)
    at Parser.parseArrowExpression (C:\Users\Arthur\Documents\Projects\alz-support\node_modules\@babel\parser\lib\index.js:6847:10)

```

After adding the helper part of your jasmine.json  this is what I'm getting:
```
$ jasmine
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '../..'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Arthur\Documents\Projects\alz-support\spec\support\loadS.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

```

**Comment by arthurgeron** [comment]
This is my .babelrc : 
```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "esmodules": true,
        "node": "current"
      }
    }]
  ]
}
```

This is my package.json:

```
{
  "name": "secret",
  "version": "0.1.0",
  "private": true,
  "main": "./public",
  "scripts": {
    "start": "npm run dev",
    "dev": "./node_modules/.bin/cross-env NODE_ENV=development ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --content-base public/ --port 4444 --colors --progress --mode development",
    "dev:prod": "./node_modules/.bin/cross-env NODE_ENV=production ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --content-base public/ --port 4444 --colors --progress --mode production",
    "build": "./node_modules/.bin/cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production",
    "lint": "./node_modules/.bin/standard",
    "lint:fix": "./node_modules/.bin/standard --fix",
    "test": "./node_modules/.bin/babel-node spec/run.js"
  },
  "devDependencies": {
    "@babel/node": "^7.0.0-beta.51",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "bootstrap": "^4.1.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "domurl": "^2.1.9",
    "eslint": "^4.19.1",
    "ghooks": "^2.0.4",
    "hson-loader": "^2.0.0",
    "html-loader": "^0.5.5",
    "jasmine": "^3.1.0",
    "jest": "^23.1.0",
    "jquery": "^3.3.1",
    "json-loader": "^0.5.7",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.2",
    "nib": "^1.1.2",
    "path-here": "^1.1.1",
    "popper.js": "^1.14.3",
    "s-js": "^0.4.8",
    "standard": "^11.0.1",
    "standard-loader": "^6.0.1",
    "style-loader": "^0.21.0",
    "surplus": "^0.5.2",
    "surplus-loader": "^0.5.0",
    "url-loader": "^1.0.1",
    "webpack": "^4.12.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"
  },
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.51",
    "@babel/core": "^7.0.0-beta.51",
    "@babel/preset-env": "^7.0.0-beta.51",
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-solid": "^5.0.13"
  },
  "config": {
    "ghooks": {
      "pre-commit": "npm run lint"
    }
  },
  "standard": {
    "parser": "babel-eslint",
    "exclude": "/node_modules/",
    "error": false,
    "snazzy": true,
    "quiet": true,
    "emitError": false,
    "failOnError": false,
    "failOnWarning": false,
    "ignore": [
      "**/*.test.js",
      "**/*.mock.js"
    ]
  }
}

```

**Comment by arthurgeron** [comment]
So.. I realized what "loadS.js"  was meant to do, change it to:
` (eval || null)('this').S = require('s-js')`

**Comment by arthurgeron** [comment]
But now I'm getting this:
```
C:\Users\Arthur\Documents\Projects\alz-support\app\components\login-modal\login-modal.js:1
(function (exports, require, module, __filename, __dirname) { import {isUndefined, includes} from 'lodash'

```

**Comment by adamhaile** [comment]
Ah, OK, that clears up some.  So your first error up there, about 'unexpected token', says that you're using Surplus JSX, but it's not being run through the Surplus compiler before your tests run.

It looks from your package.json that you're using webpack and surplus-loader.  The way I've usually done similar things is to have a webpack.test.js that compiles the tests, including running surplus-loader on them, then karma.conf.js points to the output of that compilation.  Does that make sense?

**Comment by arthurgeron** [comment]
Thanks for the suggestion, I figured using webpack as a preprocessor "should" fix the issue, but it didn't lol.

I've set  my karma.conf.js to this: 
```
// Karma configuration
// Generated on Sun Nov 23 2014 22:27:27 GMT-0500 (EST)

module.exports = function (config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // list of files / patterns to load in the browser
    files: [{ pattern: 'spec/*spec.js', watched: true }],

    // list of files to exclude
    exclude: [
      'app',
      'public',
      'node_modules'
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'spec/*spec.js': [ 'webpack' ]
    },

    webpack: {
      // karma watches the test entry points
      // (you don't need to specify the entry option)
      // webpack watches dependencies

      // webpack configuration
    },

    webpackMiddleware: {
      // webpack-dev-middleware configuration
      // i. e.
      stats: 'errors-only'
    },
    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // If browser does not capture in given timeout [ms], kill it
    captureTimeout: 60000,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  })
}
```

this is my webpack.config:
```
const exclude = /node_modules/
const include = /app|node_modules\/bootstrap\/dist/
const nib = require('nib')
const here = require('path-here')
const packageJson = require('./package.json')
const prod = process.env.NODE_ENV === 'production'
module.exports = {
  entry: [
    './public/index.html',
    './app/index.js'
  ],
  output: {
    path: here('/public'),
    filename: 'bundle.js'
  },
  devtool: !prod ? 'source-map' : undefined,
  module: {
    rules: [
      {
        test: /.js$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: true
            }
          },
          'surplus-loader',
          {
            loader: 'standard-loader',
            options: packageJson.standard
          }
        ],
        exclude
      },
      {test: /\.css$/, use: [{loader: 'style-loader'}, {loader: 'css-loader'}]},
      {test: /\.html$/, use: [{loader: 'html-loader', options: {ignoreCustomFragments: [/\{\{.*?}}/], minimize: true}}]},
      {test: /\.jpg$/, use: [{loader: 'url-loader', options: {mimetype: 'image/jpg'}}], include},
      {test: /\.png$/, use: [{loader: 'url-loader', options: {mimetype: 'image/png'}}], include},
      {test: /\.html$/, use: [{loader: 'html-loader', options: {ignoreCustomFragments: [/\{\{.*?}}/], minimize: true}}], include},
      {test: /\.json$/, use: [{loader: 'json-loader'}], include},
      {test: /\.less$/, use: [{loader: 'style-loader'}, {loader: 'css-loader'}, {loader: 'less-loader'}], include},
      {test: /\.styl$/, use: [{loader: 'style-loader'}, {loader: 'css-loader'}, {loader: 'stylus-loader'}, {loader: 'stylus-loader', options: {use: [nib()]}}], include},
      {test: /\.hson$/, use: [{loader: 'hson-loader'}], include},
      {
        test: /\.(woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: [{loader: 'url-loader', options: {mimetype: 'application/font-woff'}}],
        include: include
      },
      {
        test: /\.(ttf)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: [{loader: 'url-loader', options: {mimetype: 'application/font-sfnt'}}],
        include: include
      },
      {
        test: /\.(eot)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: [{loader: 'url-loader', options: {mimetype: 'application/vnd.ms-fontobject'}}],
        include: include
      },
      {
        test: /\.(svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: [{loader: 'url-loader', options: {mimetype: 'image/svg+xml'}}],
        include: include
      }
    ]
  },
  resolve: {
    alias: {
      'local-storage': here('/app/services/local-storage'),
      'alianza-api': here('/app/services/api/alianza-api.js'),
      'zendesk': here('/app/services/zendesk/zendesk.js'),
      'alert': here('/app/services/alert/alert.js')
    }
  },
  mode: prod ? 'production' : 'development'
}
```

By the way, thanks for being enduring and helping me out :)

**Comment by arthurgeron** [comment]
oooooh, I should've also imported my webpack config (see how 'webpack' config object is empty) ! I'm dealing with other errors now, will let you know if it all works (for future reference)

**Comment by arthurgeron** [comment]
Basically, I had to do 2 things, 1 a helper in jasmine must be set, in there you must required your main index.js file so all dependencies (basically everything) gets loaded properly.
Also that should be set in karma.conf.js `files` property before anything else (with webpack as a preprocessor).
After that everything runs just fine :).

By the way  Thank You @adamhaile  !

So now my project uses babel, karma, jasmine and webpack, for anyone that gets here with the similar issues please try a config similar to mine:

jasmine.json:
```
{
  "spec_dir": "spec",
  "spec_files": [
    "*spec.js"
  ],
  "helpers": [
    "support/loadGlobals.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

karma.conf.js (yes I use a nyancat reporter):
```
// Karma configuration
const webpack = require('./webpack.config') // loads your webpack config
const prod = process.env.NODE_ENV === 'production'
module.exports = function (config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // list of files / patterns to load in the browser
    files: [
      'spec/support/loadGlobals.js',
      { pattern: 'spec/*spec.js', watched: true }
    ],

    // list of files to exclude
    exclude: [
      'app',
      'public',
      'node_modules'
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'spec/support/loadGlobals.js': [ 'webpack' ],
      'spec/*spec.js': [ 'webpack' ]
    },

    webpack,

    webpackMiddleware: {
      // webpack-dev-middleware configuration
      // i. e.
      stats: 'errors-only'
    },
    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: prod ? ['progress'] : ['nyan'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_ERROR,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: !prod,

    // If browser does not capture in given timeout [ms], kill it
    captureTimeout: prod ? undefined : 60000,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [prod ? 'Firefox' : 'Chrome'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: prod
  })
}
```

my loadGlobals.js (yes it's that simple) : 
```
require('../../app/index.js') // basically this should be the entry file in your webpack.config.js
```
my babelrc:
```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["last 1 versions"],
        "node": "current"
      }
    }]
  ]
}
```
npm script I use to run my tests:
```
"test": "./node_modules/.bin/cross-env NODE_ENV=development ./node_modules/.bin/karma start"
```
